#!/bin/bash
# tomcat startup script for the Tomcat server
# chkconfig: 345 80 20
# description: start the tomcat deamon
# Source function library
CATALANA_HOME=/root/tomcat/apache-tomcat-6.0.53
export CATALINA_HOME
case "$1" in
start)
echo "Start Tomcat....."
$CATALANA_HOME/bin/startup.sh
;;
stop)
echo "Stopping Tomcat..."
$CATALANA_HOME/bin/shutdown.sh
;;
restart)
echo "Stopping Tomcat..."
$CATALANA_HOME/bin/shutdown.sh
sleep 2
echo
echo "Starting Tomcat..."
$CATALANA_HOME/bin/startup.sh
;;
*)
echo "Usage: $prog {start|stop|restart}"
;;
esac
exit 0
